### ISSUE TITLE
如何构建?

### ISSUE THREAD

**Issue by LegendaryZealot** [suxin1412/suos#1]
如何构建？我在头条上看见了视频，但是不知道硬件之时，可以在README里面更新一下，硬件，编译工具么？

**Comment by WangTingZheng** [comment]
您可以看看这个视频：https://www.bilibili.com/video/av54745656 以及up主空间里相关的几个视频，虽然我没试过，但是看up操作应该是这样的：
- 确保自己的开发板与up主的是一致的
- 打开keil，导入工程
- 新建一个.c文件，在文件内创建若干个函数用来写多个进程要执行的东西
- 在这个文件中引入os.h头文件
- 写一个main_t函数，在它里面用`Create_Progress()`函数执行上面写的函数来创建进程

**Comment by LegendaryZealot** [comment]
谢谢恢复

**Comment by LegendaryZealot** [comment]
谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 王听正 <notifications@github.com&gt;
发送时间: 2020年3月7日 22:51
收件人: suxin1412/suos <suos@noreply.github.com&gt;
抄送: li zhuang <875626439@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[suxin1412/suos] 如何构建? (#1)




您可以看看这个视频：https://www.bilibili.com/video/av54745656 以及up主空间里相关的几个视频，虽然我没试过，但是看up操作应该是这样的：
  
确保自己的开发板与up主的是一致的 

打开keil，导入工程 

新建一个.c文件，在文件内创建若干个函数用来写多个进程要执行的东西 

在这个文件中引入os.h头文件 

写一个main_t函数，在它里面用Create_Progress()函数执行上面写的函数来创建进程
